######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += main.hh Textbox.hh Peer.hh Messages.hh
SOURCES += main.cc Textbox.cc Peer.cc Messages.cc
